// Generated by CoffeeScript 1.3.3
(function() {

  exports.common = {
    storage: {
      host: 'localhost',
      database: 'server_dev',
      user: 'qirogami_user',
      password: 'password'
    },
    re: /^foo$/
  };

  exports.development = {};

  exports.test = {
    storage: {
      database: 'server_test'
    }
  };

  exports.production = {
    storage: {
      database: 'server_production'
    }
  };

}).call(this);
